VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "PreviewTxt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Private srcStr As String

Private Sub Class_Initialize()
  srcStr = ""
End Sub

Public Function setText(ByVal srcTxt As String) As String
Dim i As String
srcStr = srcTxt
i = srcStr
setText = i
End Function
